# Generated by Django 3.1.3 on 2020-12-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201204_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='type',
            field=models.CharField(default='d', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='type',
            field=models.CharField(default='p', max_length=20),
        ),
    ]
