# Generated by Django 3.1.3 on 2020-12-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201205_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='type',
            new_name='user_type',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='type',
            new_name='user_type',
        ),
    ]
